<?xml version="1.0"?>
<robot name="diffdrive_gazebo" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="/home/arthike/workspaces/pimouse_start/src/raspimouse_description/urdf/common.xacro" />

  <xacro:macro name="diffdrive_gazebo" params="publish_tf publish_jointstate robot_namespace">
    <gazebo>
      <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
        <!-- Name of robot namespace of DiffDriveController -->
        <robotNamespace>${robot_namespace}</robotNamespace>

        <alwaysOn>true</alwaysOn>

        <updateRate>50</updateRate>

        <!-- Set to true to swap right and left wheels, defaults to true -->
        <legacyMode>false</legacyMode>
        <rosDebugLevel>na</rosDebugLevel>

        <!-- Name of left joint, defaults to `left_joint` -->
        <left_joint>left_wheel_joint</left_joint>
        <!-- Name of right joint, defaults to `right_joint` -->
        <right_joint>right_wheel_joint</right_joint>
        <robot_base_frame>base_footprint</robot_base_frame>
        <!-- Topic to receive geometry_msgs/Twist message commands, defaults to `cmd_vel` -->
    
        <odometry_frame>odom</odometry_frame>
        <!-- Odometry source, 0 for ENCODER, 1 for WORLD, defaults to WORLD -->
        <odometry_source>1</odometry_source>

        <!-- Phisical wheel params -->
        <wheel_separation>${wheel_separation}</wheel_separation>
        <wheel_diameter>${wheel_radius*2.0}</wheel_diameter>
        <!-- Maximum torque which the wheels can produce, in Nm, defaults to 5 Nm -->
        <max_wheel_torque>500</max_wheel_torque>
        <!-- Wheel acceleration, in rad/s^2, defaults to 0.0 rad/s^2 -->
        <max_wheel_acceleration>0</max_wheel_acceleration>

        <!-- Set to true to publish /odom (nav_msgs::Odometry), defaults to true -->
        <publish_odom>${publish_tf}</publish_odom>
        <!-- Set to true to publish transforms for the wheel links, defaults to false -->
        <publish_wheel_tf>${publish_tf}</publish_wheel_tf>
        <!-- Set to true to publish transforms for the odometry, defaults to true -->
        <publish_odom_tf>${publish_tf}</publish_odom_tf>
        <!-- Set to true to publish sensor_msgs/JointState on /joint_states for the wheel joints, defaults to false -->
        <publish_jointstate>${publish_jointstate}</publish_jointstate>
      </plugin>
    </gazebo>
  </xacro:macro>
</robot>