controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

differential_drive_controller:
  ros__parameters:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.0925
    wheel_radius: 0.024
    publish_rate: 50.0  # Hz
